name: "Terraform Apply"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - master

jobs:
  terraform-plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
       
      # Static analysis of Terraform templates to spot potential security issues
      # Marketplace: https://github.com/marketplace/actions/terraform-security-scan
    #  - name: "Setup - Security Scan"
    #    uses: triat/terraform-security-scan@v1


      # Provides AWS credentials to Terraform
      # By default, Terraform checks the home directory for a .aws folder with a credential file
      # Documentation: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html
      - name: "Setup - Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
                
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
            
         
        #Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform apply"
        uses: hashicorp/setup-terraform@v1.0.1

      - name: "Terraform apply"
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo '${{ secrets.SSH_PRIVATE_KEY }}' >> ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          echo "github.com ssh-rsa ${{ env.GITHUB_COM_SSH_RSA_PUBLIC_KEY }}" >> ~/.ssh/known_hosts
          chmod 400 ~/.ssh/known_hosts
          make plan 
          make apply
          make build
          make publish
          make deploy-wp
          

